=== angelinapolishchuk/Library/Cards.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Cards">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Card" maxOccurs="unbounded" minOccurs="1" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="AcceptanceDate" type="xs:string" />
                            <xs:element name="ReturnDate" type="xs:string" />
                            <xs:element name="LibraryId" type="xs:unsignedInt"/>
                        </xs:sequence>
                        <xs:attribute name="CardId" type="xs:unsignedInt" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:simpleType name="DefinedCourse">
        <xs:restriction base="xs:unsignedByte">
            <xs:minInclusive value="1"/> <xs:maxInclusive value="4"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== angelinapolishchuk/Library/Cards.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Cards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="Cards.xsd">
    <Card CardId = "1">
        <AcceptanceDate>2022-02-03</AcceptanceDate>
        <ReturnDate>2022-03-03</ReturnDate>
        <LibraryId>1</LibraryId>
    </Card>
    <Card CardId = "2">
        <AcceptanceDate>2022-02-03</AcceptanceDate>
        <ReturnDate>2022-03-03</ReturnDate>
        <LibraryId>2</LibraryId>
    </Card>
</Cards>
